In [ ]:
import numpy as np
a=np.array([4,2,7])
print(a)

[4 2 7]


In [ ]:
import numpy as np 
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a+1)
print(b+1)
print(a+b)

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]
[[ 6  8]
 [10 12]]


In [ ]:
import numpy as np
a=np.array([[6,0,4],[2,3,1]])
print("type of array is",type(a))

type of array is <class 'numpy.ndarray'>


In [ ]:

import numpy as np
a=np.array([[6,0,2],[3,2,4]])
print("shape of array is",a.shape)
print("dimension of array",a.ndim)

shape of array is (2, 3)
dimension of array 2


In [ ]:
import numpy as np
a=np.array([[5,6,4],[1,2,3]])

print("max no of element",a.max(axis=0))
print("min no of element",a.min(axis=0))
print("max no of element",a.max(axis=1))
print("min no of element",a.min(axis=1))

max no of element [5 6 4]
min no of element [1 2 3]
max no of element [6 3]
min no of element [4 1]


In [ ]:
import numpy as np
a=np.arange(0,10,2,int)
print(a)
b=np.arange(0.0,15.6,3.2,float)
print(b)

[0 2 4 6 8]
[ 0.   3.2  6.4  9.6 12.8]


In [ ]:
import numpy as np 
print(np.char.add(["HELLO""PYTHON"],["PROGRAM"]))

['HELLOPYTHONPROGRAM']


In [ ]:
import numpy as numpy
print(np.char.multiply(["python"],4))

['pythonpythonpythonpython']


In [ ]:
import numpy as np
print(np.char.upper(["pyThon"]))
print(np.char.lower(["PYthoN"]))

['PYTHON']
['python']
